Package dependency support
r7com/buildable pull request #7
Opened 2016-10-24 18:24 UTC by acamargo

Allow declaration of dependent packages using buildable.yml

2016-10-24 20:03 UTC, alexandreprates requested changes

2016-10-24 20:03 UTC, alexandreprates commented on lib/core_ext/hash.rb
> +    [].tap do |tokens|
Acho que não cabe ao #to_params resolver este problema, eu recomendaria usar um hash com #compare_by_identity (https://ruby-doc.org/core-1.9.3/Hash.html#method-i-compare_by_identity) permitindo assim criar mais de uma chave com a mesma string e deixando esta lógica dentro da recipe

2016-10-25 13:01 UTC, alexandreprates requested changes
A lógica está ok, só falta colocar o novo parametro (depends) no template que gera o arquivo .buidlable.yml

2016-10-25 15:20 UTC, acamargo commented
deixei lá, comentado https://github.com/acamargo/buildable/blob/master/templates/.buildable.yml.erb#L7

2016-10-25 16:21 UTC, merged